### ISSUE TITLE
typo in build.boot

### ISSUE THREAD

**Issue by philcruz** [framework-one/framework-one.github.io#22]
http://framework-one.github.io/documentation/4.0/cfml-and-clojure.html

in two instances there is a typo in the build.boot 

`:dependencies '[[org.clojre/clojure "1.7.0"]])
`
should be

`:dependencies '[[org.clojure/clojure "1.7.0"]])`

**Comment by seancorfield** [comment]
Good catch! Thank you! Fixed. I also took the opportunity to update the Clojure versions (1.8.0 is now the stable release, not 1.7.0, and early alpha builds of 1.9.0 are available), as well as add a note about the (external) `boot-new` task for creating new projects.
