### ISSUE TITLE
Explain how security controllers checkAuthorization method is called

### ISSUE THREAD

**Issue by displague** [framework-one/framework-one.github.io#3]
At https://github.com/framework-one/framework-one.github.io/blob/master/documentation/developing-applications.html#L201-L211 setupRequest is said to call a controller action.  Since controller actions are normally sent rc, and rc has not been established yet, what parameters are sent to this action?  

If the action is sent rc, is the action expected to add properties to rc?

**Comment by seancorfield** [comment]
As that document says "This **queues up a call** to that controller at the start of the request processing". It does not "call a controller action". Once `rc` is set up -- "at the start of the request processing" -- then the queued up controller action is called, and passed `rc`, just like any other controller call.

Perhaps you should look at the examples? In particular, there's a version of the user manager example that has exactly this construct:

https://github.com/framework-one/fw1/blob/master/examples/userManagerAccessControl/Application.cfc#L22

BTW, questions like this really belong on the mailing list, not in issues against the documentation. If you think you can provide a clarification to the documentation, feel free to submit a Pull Request.
